package com.eldrix.terminology.snomedct.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.eldrix.terminology.snomedct.Concept;

/**
 * Class _CachedParentConcepts was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CachedParentConcepts extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CHILD_CONCEPT_ID_PK_COLUMN = "child_concept_id";
    public static final String PARENT_CONCEPT_ID_PK_COLUMN = "parent_concept_id";

    public static final Property<Long> CHILD_CONCEPT_ID = new Property<Long>("childConceptId");
    public static final Property<Long> PARENT_CONCEPT_ID = new Property<Long>("parentConceptId");
    public static final Property<Concept> CHILD_CONCEPT = new Property<Concept>("childConcept");
    public static final Property<Concept> PARENT_CONCEPT = new Property<Concept>("parentConcept");

    public void setChildConceptId(Long childConceptId) {
        writeProperty("childConceptId", childConceptId);
    }
    public Long getChildConceptId() {
        return (Long)readProperty("childConceptId");
    }

    public void setParentConceptId(Long parentConceptId) {
        writeProperty("parentConceptId", parentConceptId);
    }
    public Long getParentConceptId() {
        return (Long)readProperty("parentConceptId");
    }

    public void setChildConcept(Concept childConcept) {
        setToOneTarget("childConcept", childConcept, true);
    }

    public Concept getChildConcept() {
        return (Concept)readProperty("childConcept");
    }


    public void setParentConcept(Concept parentConcept) {
        setToOneTarget("parentConcept", parentConcept, true);
    }

    public Concept getParentConcept() {
        return (Concept)readProperty("parentConcept");
    }


}
