package com.eldrix.terminology.snomedct.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _CrossMapTarget was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CrossMapTarget extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String TARGET_ID_PK_COLUMN = "target_id";

    public static final Property<String> ADVICE = new Property<String>("advice");
    public static final Property<String> CODES = new Property<String>("codes");
    public static final Property<String> RULE = new Property<String>("rule");
    public static final Property<String> SCHEME_ID = new Property<String>("schemeId");
    public static final Property<Long> TARGET_ID = new Property<Long>("targetId");

    public void setAdvice(String advice) {
        writeProperty("advice", advice);
    }
    public String getAdvice() {
        return (String)readProperty("advice");
    }

    public void setCodes(String codes) {
        writeProperty("codes", codes);
    }
    public String getCodes() {
        return (String)readProperty("codes");
    }

    public void setRule(String rule) {
        writeProperty("rule", rule);
    }
    public String getRule() {
        return (String)readProperty("rule");
    }

    public void setSchemeId(String schemeId) {
        writeProperty("schemeId", schemeId);
    }
    public String getSchemeId() {
        return (String)readProperty("schemeId");
    }

    public void setTargetId(Long targetId) {
        writeProperty("targetId", targetId);
    }
    public Long getTargetId() {
        return (Long)readProperty("targetId");
    }

}
