package com.eldrix.terminology.snomedct.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.eldrix.terminology.snomedct.Concept;

/**
 * Class _Description was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Description extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String DESCRIPTION_ID_PK_COLUMN = "description_id";

    public static final Property<Long> DESCRIPTION_ID = new Property<Long>("descriptionId");
    public static final Property<Integer> DESCRIPTION_STATUS_CODE = new Property<Integer>("descriptionStatusCode");
    public static final Property<Integer> DESCRIPTION_TYPE_CODE = new Property<Integer>("descriptionTypeCode");
    public static final Property<String> INITIAL_CAPITAL_STATUS = new Property<String>("initialCapitalStatus");
    public static final Property<String> LANGUAGE_CODE = new Property<String>("languageCode");
    public static final Property<String> TERM = new Property<String>("term");
    public static final Property<Concept> CONCEPT = new Property<Concept>("concept");

    public void setDescriptionId(Long descriptionId) {
        writeProperty("descriptionId", descriptionId);
    }
    public Long getDescriptionId() {
        return (Long)readProperty("descriptionId");
    }

    public void setDescriptionStatusCode(Integer descriptionStatusCode) {
        writeProperty("descriptionStatusCode", descriptionStatusCode);
    }
    public Integer getDescriptionStatusCode() {
        return (Integer)readProperty("descriptionStatusCode");
    }

    public void setDescriptionTypeCode(Integer descriptionTypeCode) {
        writeProperty("descriptionTypeCode", descriptionTypeCode);
    }
    public Integer getDescriptionTypeCode() {
        return (Integer)readProperty("descriptionTypeCode");
    }

    public void setInitialCapitalStatus(String initialCapitalStatus) {
        writeProperty("initialCapitalStatus", initialCapitalStatus);
    }
    public String getInitialCapitalStatus() {
        return (String)readProperty("initialCapitalStatus");
    }

    public void setLanguageCode(String languageCode) {
        writeProperty("languageCode", languageCode);
    }
    public String getLanguageCode() {
        return (String)readProperty("languageCode");
    }

    public void setTerm(String term) {
        writeProperty("term", term);
    }
    public String getTerm() {
        return (String)readProperty("term");
    }

    public void setConcept(Concept concept) {
        setToOneTarget("concept", concept, true);
    }

    public Concept getConcept() {
        return (Concept)readProperty("concept");
    }


}
